//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietBangLuong
    {
        public string Thang { get; set; }
        public string MaNV { get; set; }
        public string MaTinhLuong { get; set; }
        public string SoNgayCong { get; set; }
    
        public virtual BangLuong BangLuong { get; set; }
        public virtual TinhLuong TinhLuong { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
