//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Luan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.BangLuongs = new HashSet<BangLuong>();
        }
    
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public string MucLuong { get; set; }
        public string Phai { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string DThoai { get; set; }
        public string TrinhDoChuyenMon { get; set; }
        public string GhiChu { get; set; }
        public string MaPB { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BangLuong> BangLuongs { get; set; }
        public virtual ChiTietBangLuong ChiTietBangLuong { get; set; }
        public virtual PhongBan PhongBan { get; set; }
    }
}
